# Generated by Django 4.2.30 on 2026-05-01 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="volunteerrequest",
            name="shelter_name",
        ),
        migrations.AddField(
            model_name="adoptionrequest",
            name="questionnaire_result",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="adoption_requests",
                to="core.questionnaireresult",
            ),
        ),
        migrations.AddField(
            model_name="volunteerrequest",
            name="shelter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="volunteer_requests",
                to="core.shelter",
            ),
        ),
    ]
