# Generated by Django 4.2.30 on 2026-05-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_volunteerrequest_shelter_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteerrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Розглядається"),
                    ("APPROVED", "Схвалено"),
                    ("REJECTED", "Відхилено"),
                    ("CANCELLED", "Скасовано"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
