# Generated by Django 4.2.30 on 2026-06-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_alter_adoptionrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
